import { useEffect, useState } from "react";

type Order={id:string;raffleTitle:string;buyerName:string;buyerPhone:string;total:string;status:string;paymentStatus?:string;createdAt:string};
const money=(v:string)=>`R$ ${Number(v).toFixed(2).replace(".",",")}`;
export default function OrdersPage({raffleId}:{raffleId?:string}){
 const [orders,setOrders]=useState<Order[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 const load=async()=>{setLoading(true);const qs=new URLSearchParams({status});if(search)qs.set("search",search);if(raffleId)qs.set("raffleId",raffleId);const r=await fetch(`/api/admin/orders?${qs}`,{credentials:"include"});setOrders(r.ok?(await r.json()).orders??[]:[]);setLoading(false)};
 useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id)},[search,status,raffleId]);
 const action=async(id:string,path:string)=>{if(!confirm(path.includes("confirm")?"Confirmar recebimento deste Pix?":"Cancelar este pedido?") )return;setBusy(id);await fetch(`/api/admin/orders/${id}/${path}`,{method:"POST",credentials:"include"});await load();setBusy("")};
 return <main className="admin-orders"><header><span className="section-label">RIFA X · ADMIN</span><h1>Pedidos</h1><p>Pesquise comprador, telefone ou código do pedido.</p></header><div className="search-box"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, telefone ou pedido…" inputMode="search"/></div><div className="filters">{["ALL","PENDING","PAID","EXPIRED","CANCELLED"].map(s=><button className={status===s?"active":""} onClick={()=>setStatus(s)} key={s}>{s==="ALL"?"Todos":s==="PENDING"?"Pendentes":s==="PAID"?"Pagos":s==="EXPIRED"?"Expirados":"Cancelados"}</button>)}</div>{loading?<p>Carregando…</p>:orders.length===0?<div className="empty"><strong>Nenhum pedido encontrado</strong><p>Tente alterar a busca ou o filtro.</p></div>:<section className="order-list">{orders.map(o=><article className="order-row" key={o.id}><div className="order-main"><strong>{o.buyerName}</strong><span>{o.buyerPhone}</span><small>{o.raffleTitle} · {new Date(o.createdAt).toLocaleString("pt-BR")}</small></div><div className="order-meta"><b>{money(o.total)}</b><span className={`status status-${o.status.toLowerCase()}`}>{o.status}</span></div>{o.status==="PENDING"&&<div className="order-actions"><button disabled={busy===o.id} onClick={()=>action(o.id,"confirm-payment")}>{busy===o.id?"…":"Confirmar Pix"}</button><button disabled={busy===o.id} onClick={()=>action(o.id,"cancel")}>Cancelar</button></div>}<a href={`/admin/orders/${o.id}`}>Ver detalhes ›</a></article>)}</section>}</main>;
}
