import { useEffect, useState } from "react";

type Raffle={id:string;title:string;slug:string;description?:string;status:string;ticketPrice:string;numbersCount:number;drawMethod:string;drawAt?:string|null;pixKey?:string;pixCity?:string;prizes?:{id:string;title:string;description?:string}[]};
type Summary={available:number;reserved:number;sold:number;total:number;revenue:string};
const money=(v:string|number)=>`R$ ${Number(v).toFixed(2).replace(".",",")}`;
export default function RaffleDetailPage({id}:{id:string}){
 const [raffle,setRaffle]=useState<Raffle|null>(null),[summary,setSummary]=useState<Summary|null>(null),[tab,setTab]=useState("overview"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{const r=await fetch(`/api/admin/raffles/${id}`,{credentials:'include'});if(!r.ok){setError('Não foi possível carregar a rifa.');return}const d=await r.json();setRaffle(d.raffle);setSummary(d.summary)};
 useEffect(()=>{void load()},[id]);
 const action=async(path:string,method='POST')=>{setBusy(true);setError('');const r=await fetch(`/api/admin/raffles/${id}/${path}`,{method,credentials:'include'});if(!r.ok)setError((await r.json()).error??'Operação não realizada.');else await load();setBusy(false)};
 if(error&&!raffle)return <main className="admin-page"><p role="alert">{error}</p></main>;
 if(!raffle)return <main className="admin-page"><p>Carregando…</p></main>;
 const sold=summary?.sold??0,total=summary?.total??raffle.numbersCount,progress=total?Math.round(sold/total*100):0;
 return <main className="raffle-admin"><header><a href="/admin">← Dashboard</a><span className="section-label">RIFA X · ADMIN</span><h1>{raffle.title}</h1><p>/{raffle.slug}</p><div className="header-actions"><a href={`/r/${raffle.slug}`} target="_blank" rel="noreferrer">Ver rifa</a><a href={`/admin/rifas/${id}/edit`}>Editar</a>{raffle.status==='DRAFT'&&<button disabled={busy} onClick={()=>action('publish')}>Publicar</button>}{raffle.status==='ACTIVE'&&<><a href={`/admin/draws/${id}`}>Abrir sorteio</a><button disabled={busy} onClick={()=>action('unpublish')}>Despublicar</button></>}</div></header><section className="progress-card"><div><strong>{progress}%</strong><span>vendido</span></div><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{sold} de {total} números</small></section><nav className="tabs" aria-label="Seções"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Visão geral</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pedidos</button><button className={tab==='numbers'?'active':''} onClick={()=>setTab('numbers')}>Números</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Configurações</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Histórico</button></nav>{tab==='overview'&&<section className="stats"><article><span>Disponíveis</span><strong>{summary?.available??0}</strong></article><article><span>Reservados</span><strong>{summary?.reserved??0}</strong></article><article><span>Vendidos</span><strong>{sold}</strong></article><article><span>Arrecadado</span><strong>{money(summary?.revenue??0)}</strong></article><article><span>Preço</span><strong>{money(raffle.ticketPrice)}</strong></article><article><span>Sorteio</span><strong>{raffle.drawMethod==='FEDERAL_LOTTERY'?'Loteria Federal':'Rifa X'}</strong></article><div className="prizes"><h2>Prêmios</h2>{raffle.prizes?.map(p=><article key={p.id}><strong>{p.title}</strong><p>{p.description}</p></article>)}</div></section>}{tab==='orders'&&<section><h2>Pedidos</h2><p>Gerencie compradores, pagamentos e confirmações Pix.</p><a className="primary-button" href={`/admin/orders?raffle=${encodeURIComponent(id)}`}>Abrir pedidos</a></section>}{tab==='numbers'&&<section><h2>Números</h2><p>Visualize disponibilidade, reservas e vendas desta rifa.</p><a className="primary-button" href={`/admin/rifas/${id}/numeros`}>Abrir mapa de números</a></section>}{tab==='settings'&&<section><h2>Configurações</h2><a href={`/admin/rifas/${id}/edit`}>Editar dados da rifa</a><button disabled={busy} onClick={()=>action('cancel')}>Cancelar rifa</button></section>}{tab==='history'&&<section><h2>Histórico</h2><p>As alterações administrativas serão exibidas aqui a partir do audit log.</p></section>}{error&&<p role="alert">{error}</p>}</main>;
}
