import { FormEvent, useState } from "react";

type Prize={title:string;description:string;imageUrl:string};
const initialPrize=():Prize=>({title:"",description:"",imageUrl:""});
export default function RaffleFormPage(){
 const [prizes,setPrizes]=useState<Prize[]>([initialPrize()]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({title:"",slug:"",description:"",numbersCount:"100",ticketPrice:"10.00",drawMethod:"RIFA_X",drawAt:"",pixKey:"",pixCity:"",bannerUrl:""});
 const set=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");const payload={...form,numbersCount:Number(form.numbersCount),prizes:prizes.filter(p=>p.title.trim())};const r=await fetch('/api/admin/raffles',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});if(!r.ok){setError((await r.json()).error??'Não foi possível criar a rifa.');setSaving(false);return}location.href='/admin';};
 return <main className="admin-form"><header><span className="section-label">RIFA X · ADMIN</span><h1>Nova rifa</h1><p>Configure a rifa, o prêmio e o Pix.</p></header><form onSubmit={submit}><section><h2>Informações</h2><label>Título<input required value={form.title} onChange={e=>set('title',e.target.value)}/></label><label>Link<input required value={form.slug} onChange={e=>set('slug',e.target.value.toLowerCase().replace(/\s+/g,'-'))} placeholder="minha-rifa"/></label><label>Descrição<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label></section><section><h2>Números e preço</h2><div className="form-grid"><label>Quantidade<input required min="1" type="number" value={form.numbersCount} onChange={e=>set('numbersCount',e.target.value)}/></label><label>Valor por número<input required min="0.01" step="0.01" type="number" value={form.ticketPrice} onChange={e=>set('ticketPrice',e.target.value)}/></label></div></section><section><h2>Prêmio(s)</h2>{prizes.map((p,i)=><div className="prize" key={i}><label>Prêmio {i+1}<input required value={p.title} onChange={e=>setPrizes(ps=>ps.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></label><label>Descrição<textarea value={p.description} onChange={e=>setPrizes(ps=>ps.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></label>{prizes.length>1&&<button type="button" onClick={()=>setPrizes(ps=>ps.filter((_,j)=>j!==i))}>Remover</button>}</div>)}<button type="button" onClick={()=>setPrizes(p=>[...p,initialPrize()])}>+ Adicionar prêmio</button></section><section><h2>Sorteio</h2><label>Método<select value={form.drawMethod} onChange={e=>set('drawMethod',e.target.value)}><option value="RIFA_X">Rifa X — sorteio ao vivo</option><option value="FEDERAL_LOTTERY">Loteria Federal</option></select></label><label>Data do sorteio<input type="datetime-local" value={form.drawAt} onChange={e=>set('drawAt',e.target.value)}/></label></section><section><h2>Pix</h2><label>Chave Pix<input required value={form.pixKey} onChange={e=>set('pixKey',e.target.value)}/></label><label>Cidade do recebedor<input required maxLength={15} value={form.pixCity} onChange={e=>set('pixCity',e.target.value)}/></label></section>{error&&<p role="alert">{error}</p>}<button disabled={saving} type="submit">{saving?'Criando…':'Criar rifa'}</button></form></main>;
}
