import { Hono } from "hono";
import { and, eq, isNull } from "drizzle-orm";
import { createDatabase } from "@rifa-x/database";
import { auditLogs, users } from "@rifa-x/database/schema";
import { createSession, requireRole } from "../middleware/auth";
import type { AppBindings, AppVariables } from "../types";

const auth = new Hono<{ Bindings: AppBindings; Variables: AppVariables }>();
const COOKIE = "rifax_session";
const roles = ["SUPER_ADMIN","ORGANIZATION_ADMIN","COLLABORATOR"] as const;
async function hashPassword(password:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(password));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function timingSafeEqual(a:string,b:string){const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let diff=0;for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];return diff===0}
function setCookie(c:any,token:string){c.header("Set-Cookie",`${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`)}
function clearCookie(c:any){c.header("Set-Cookie",`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`)}
auth.post("/login",async c=>{try{const body=await c.req.json<{email?:string;password?:string}>();if(!body.email||!body.password)return c.json({error:"Email and password are required"},400);const db=createDatabase(c.env.DATABASE_URL);const email=body.email.trim().toLowerCase();const user=await db.query.users.findFirst({where:and(eq(users.email,email),eq(users.status,"ACTIVE"),isNull(users.deletedAt))});const passwordHash=await hashPassword(body.password);if(!user?.passwordHash||!(await timingSafeEqual(passwordHash,user.passwordHash)))return c.json({error:"Invalid credentials"},401);if(!c.env.SESSION_SECRET)return c.json({error:"Session configuration missing"},503);const token=await createSession({userId:user.id,organizationId:user.organizationId,role:user.role,expiresAt:Date.now()+8*60*60*1000},c.env.SESSION_SECRET);setCookie(c,token);return c.json({user:{id:user.id,name:user.name,email:user.email,role:user.role,organizationId:user.organizationId}})}catch(error){const message=error instanceof Error?error.message:String(error);console.error("Login failed",message.replace(/postgres(?:ql)?:\/\/[^\s]+/gi,"[redacted-database-url]").replace(/password=[^\s&]+/gi,"password=[redacted]"));return c.json({error:"Login failed","code":"LOGIN_INTERNAL_ERROR"},500)}});
auth.post("/logout",requireRole([...roles]),async c=>{clearCookie(c);return c.json({ok:true})});
auth.get("/me",requireRole([...roles]),async c=>c.json({user:c.get("auth")}));
auth.get("/admins",requireRole(["SUPER_ADMIN"]),async c=>{const db=createDatabase(c.env.DATABASE_URL);const rows=await db.query.users.findMany({where:and(eq(users.role,"ORGANIZATION_ADMIN"),isNull(users.deletedAt)),columns:{id:true,organizationId:true,name:true,email:true,status:true,createdAt:true}});return c.json({admins:rows})});
auth.post("/admins",requireRole(["SUPER_ADMIN"]),async c=>{const body=await c.req.json<{organizationId?:string;name?:string;email?:string;password?:string}>();if(!body.organizationId||!body.name?.trim()||!body.email?.trim()||!body.password||body.password.length<8)return c.json({error:"Organization, name, email and password (min. 8 chars) are required"},400);const db=createDatabase(c.env.DATABASE_URL);try{const [user]=await db.insert(users).values({organizationId:body.organizationId,name:body.name.trim(),email:body.email.trim().toLowerCase(),passwordHash:await hashPassword(body.password),role:"ORGANIZATION_ADMIN",status:"ACTIVE"}).returning({id:users.id,organizationId:users.organizationId,name:users.name,email:users.email,role:users.role});const session=c.get("auth");await db.insert(auditLogs).values({organizationId:body.organizationId,actorUserId:session.userId,action:"ADMIN_CREATED",entityType:"USER",entityId:user.id,metadata:{email:user.email}});return c.json({user},201)}catch{return c.json({error:"Unable to create administrator"},409)}});
export default auth;
